name: Deploy to EC2 on Push

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest # Run on Github's Ubuntu-server 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SCP
        run: |
          scp -i ~/.ssh/ec2_key.pem -r * ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/html/o3-landing/
